### ISSUE TITLE
detect bad HTML to prevent notebook renderer from failing

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#268]
We faced an issue (#267) with the line breaks in external notebooks which are added to the site to be detected as bad HTML which cause our notebook renderer to error out resulting in a build fail. We need to include a plugin which automatically detects occurrences of bbad HTML.

> **Gage Krumbach wrote:**
> in the long run there should probably be some plugin that detects bad HTML. I saw that the newer version of the notebook renderer recommended to use one. Especially if the notebooks are being pulled from external sources
> 
cc: @Gkrumbach07

**Comment by Gkrumbach07** [comment]
**This is the bad HTML fix**

This [plugin](https://github.com/rehypejs/rehype-sanitize) can be used on top of the [markdown renderer](https://github.com/remarkjs/react-markdown#use-remark-and-rehype-plugins-math). Could be hard to implement however due to the package not having this capability inherently at the current version we are using. Would have to do some testing to see whats possible.

**Comment by tumido** [comment]
Should be resolved by #312 and #313 since each PR is attempted to be built also with better logging about which page is being processed - minimizing the failure chance on merge.
