### ISSUE TITLE
Get any other ready-to-publish documents from continuous-deployment repo linked to this repo

### ISSUE THREAD

**Issue by oindrillac** [operate-first/operate-first.github.io-old#38]

**Comment by cfchase** [comment]
@oindrillac the docs folder might need to be cleaned up to match the standard structure or a separate publish folder might need to be made.  I ignored problematic `README.md` files in a [PR](https://github.com/operate-first/operate-first.github.io/pull/48) due to a problem building.  https://github.com/operate-first/operate-first.github.io/issues/16#issuecomment-713722463

**Comment by oindrillac** [comment]
@cfchase I agree with this. Currently we are processing a bunch of unnecessary files during the build. I think we can have a dedicated `publish` folder in our remote repos only meant to contain docs to be integrated with this repo.

**Comment by oindrillac** [comment]
An easy current fix couldbe to lint the document which is throwing an error or update the .yaml to individually link the documents which are being published.
