### ISSUE TITLE
Get rid of hardcoded / redirect to /operate-first

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io-old#97]
I want to get rid of the redirect to /operate-first and instead use an `index.md` in `/content/`
Do I need to hack https://github.com/operate-first/operate-first.github.io/blob/master/gatsby-node.js for this? And hardcode an `/` page in there? Or would I create a `/src/pages/index.js` to return the content?

I'm also ok with just configuring it in https://github.com/operate-first/operate-first.github.io/blob/master/content/toc.yaml - but it looks like the `href` needs to match the actual path on the filesystem. So I cant say:

```
href: /
path: root/index.md
```

**Comment by cfchase** [comment]
The easiest thing is to remove the redirect and  create a `src/pages/index.js` like https://github.com/operate-first/operate-first.github.io/compare/master...cfchase:change-index  Adding an index.md file under content seems to fail because it didn't seem to be able to parse the location to generate it correctly, but it's probably fixable. You can add the `/` link to the `toc.yaml` if you want, but you can just set `/` as the href for the logo, as well.

**Comment by cfchase** [comment]
Fixed in https://github.com/operate-first/operate-first.github.io/pull/99
